version: '3.7'

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    image: asia.gcr.io/primal-library-370305/my-backend:1.9
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    # ports:
    #   - 3000:3000
    # env_file:
    #   - ./.env.prod

  # # 컴퓨터이름
  # my-database:
  #   platform: linux/86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myprod10'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
